name: Lint and Build and Test

on:
  push:
    branches:
      - main
      - lab02
      - lab06

jobs:
  lint:
    runs-on: ubuntu-latest
    environment: test-env

    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.23

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Go vet complexity
        uses: shoooooman/go-complexity-analysis-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          cycloover: 10
          # halsteadover: 50
      
      - name: Install golint
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.62.2

      - name: Launch golint
        run: |
          golangci-lint run cmd/... config/... internal/... pkg/...
          if [ $? -ne 0 ]; then exit 1; fi


  test:
    needs: lint
    runs-on: ubuntu-latest
    environment: test-env

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Run test db
        run: |
          docker ps -a
          docker compose up -d postgres-test

      - name: Build testing docker-image
        env:
          POSTGRES_TEST_HOST: ${{ secrets.POSTGRES_TEST_HOST }}
          POSTGRES_TEST_PORT: ${{ secrets.POSTGRES_TEST_PORT }}
        run: |
          ls -al
          docker build -t app:v1.0.0 -f tests/Dockerfile --build-arg postgres_test_host=${POSTGRES_TEST_HOST} --build-arg postgres_test_port=${POSTGRES_TEST_PORT} . 

      - name: Run testing docker-container and launch tests
        shell: 'script --return --quiet --log-out /dev/null --command "bash -e {0}"'
        run: |
          docker run --name testing --network testing-2024_dev -it app:v1.0.0 "cd /testing-2024 && make test"
          docker cp testing:/testing-2024/tests/allure-report .
          docker cp testing:/testing-2024/tests/allure-results .

      - name: Archive code test results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-*
          
          

