name: Build and Test

on:
  push:
    branches:
      - main
      - lab02
      - lab04

jobs:
#  build:
#    runs-on: ubuntu-latest
#    environment: avito-env
#
#    steps:
#      - name: Check out repository
#        uses: actions/checkout@v2
#
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v1
#
#      - name: Run services
#        env:
#          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
#          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
#          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
#        run: |
#          export POSTGRES_USER=$POSTGRES_USER POSTGRES_PASSWORD=$POSTGRES_PASSWORD POSTGRES_DB=$POSTGRES_DB
#          docker compose up -d
#          docker logs postgres-db
#
#      - name: Check services
#        run: |
#          sleep 10
#          docker-compose ps
#
#      - name: Stop services
#        run:
#          docker compose down

  test:
    runs-on: ubuntu-latest
    environment: test-env

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Run test db
        run: |
          docker ps -a
          docker compose up -d postgres-test

      - name: Build testing docker-image
        env:
          POSTGRES_TEST_HOST: ${{ secrets.POSTGRES_TEST_HOST }}
          POSTGRES_TEST_PORT: ${{ secrets.POSTGRES_TEST_PORT }}
          PASSWORD: ${{ secrets.PASSWORD }}
          TOKEN: ${{ secrets.TOKEN }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_USER }}
          POSTGRES_DB: ${{ secrets.POSTGRES_USER }}
          KEY: ${{ secrets.KEY }} 
        run: |
          ls -al
          docker build -t app:v1.0.0 -f tests/Dockerfile --build-arg postgres_test_host=${POSTGRES_TEST_HOST} --build-arg postgres_test_port=${POSTGRES_TEST_PORT} --build-arg token=${TOKEN} --build-arg password=${PASSWORD} . 

      - name: Run testing docker-container and launch tests
        shell: 'script --return --quiet --log-out /dev/null --command "bash -e {0}"'
        run: |
          docker run --name testing --network testing-2024_dev -it app:v1.0.0 "cd /testing-2024 && make test"
          docker cp testing:/testing-2024/tests/allure-report .
          docker cp testing:/testing-2024/tests/allure-results .

      - name: Run docker-container and launch auth test
        shell: 'script --return --quiet --log-out /dev/null --command "bash -e {0}"'
        env:
          TOKEN: ${{ secrets.TOKEN }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          KEY: ${{ secrets.KEY }} 
        run: |
          export POSTGRES_USER=${POSTGRES_USER} POSTGRES_PASSWORD=${POSTGRES_PASSWORD} POSTGRES_DB=${POSTGRES_DB} KEY=${KEY} TOKEN=${TOKEN}
          docker compose up -d postgres
          sleep 5
          docker compose up -d migrate
          docker build -t goback -f Dockerfile .
          sleep 5
          docker compose up -d backend1 backend2 backend3 nginx
          sleep 5
          cd tests && (go test . -tags=auth || true)
          docker logs backend1
          docker logs backend2
          docker logs backend3


      - name: Archive code test results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-*
          
          

