name: Build and Test

on:
  push:
    branches:
      - main
      - lab02

jobs:
#  build:
#    runs-on: ubuntu-latest
#    environment: avito-env
#
#    steps:
#      - name: Check out repository
#        uses: actions/checkout@v2
#
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v1
#
#      - name: Run services
#        env:
#          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
#          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
#          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
#        run: |
#          export POSTGRES_USER=$POSTGRES_USER POSTGRES_PASSWORD=$POSTGRES_PASSWORD POSTGRES_DB=$POSTGRES_DB
#          docker compose up -d
#          docker logs postgres-db
#
#      - name: Check services
#        run: |
#          sleep 10
#          docker-compose ps
#
#      - name: Stop services
#        run:
#          docker compose down

  test:
    runs-on: ubuntu-latest
    environment: avito-env

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Run test db
        run: |
          docker compose up -d postgres-test

      - name: Build testing docker-image
        run: |
          ls -al
          docker build -t app:v1.0.0 -f tests/Dockerfile .

      - name: Run testing docker-container and launch tests
        shell: 'script --return --quiet --log-out /dev/null --command "bash -e {0}"'
        run: |
          docker run --rm -it app:v1.0.0 "cd /testing-2024 && make test"
          
          

